--- 
env:
  secrets-manager:
    AWS_ACCESS_KEY_ID: arn:aws:secretsmanager:us-east-2:202830530179:secret:mentorRepo/tutorial/apiuser_creds-x4ZE9J:aws_access_key_id
    AWS_SECRET_ACCESS_KEY: arn:aws:secretsmanager:us-east-2:202830530179:secret:mentorRepo/tutorial/apiuser_creds-x4ZE9J:aws_secret_access_key
#    dockerpwd_antonyjohnpaul23us: mentorRepo/tutorial/buildSecrets:dockerhub_key1

phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t antonyjohnpaul23usgmail/pyapp FargateECSAppWithLoadbalancer-mainline/."
      #- "docker tag antonyjohnpaul23usgmail/mentor-node-server antonyjohnpaul23usgmail/mentor-node-server:latest"
      - "docker tag antonyjohnpaul23usgmail/pyapp 202830530179.dkr.ecr.us-east-2.amazonaws.com/pyapp:latest"
      
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      #- "export AWS_ACCESS_KEY_ID=$aws_access_key_id"
      #- "export AWS_SECRET_ACCESS_KEY=$aws_secret_access_key"
      - "echo $AWS_ACCESS_KEY_ID"
      #- "docker push antonyjohnpaul23usgmail/mentor-node-server:latest"
      - "docker push 202830530179.dkr.ecr.us-east-2.amazonaws.com/pyapp:latest"
  pre_build: 
    commands: 
      - echo Logging in to Amazon ECR.... 
      - aws --version
      # update the following line with your own region
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 202830530179.dkr.ecr.us-east-2.amazonaws.com
      #- $(aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 202830530179.dkr.ecr.us-east-2.amazonaws.com)
      #- $(aws ecr get-login-password --region us-east-2)
      #- "docker login --username=\"antonyjohnpaul23usgmail\" --password=\"access2india\""
version: 0.1
